### ISSUE TITLE
 epo documentation V3.1.0 : General Reference

### ISSUE THREAD

**Issue by muricna** [OP-TED/epo-docs#13]
**Suggestion re improving Documentation**
I see the business overview (under reference documents in the v3.1.0 however I do not find it in the 4.0.0-rc.1
I take it will appear in the 3.0.0-rc.1?
I like this

What I am not so keen on is the release overview when I look in the release overview of the previous versions we have each time the same standard text.  I would suggest moving the release overview abstract from the previous versions to the business overview and remove the methodology.

**Comment by NPJ-OP-LUX** [comment]
Currently that is correct, we need the main-new main merge to happen first because the business overview is only on new_main at the moment and this branch is not public yet. After the merge, I will update the LH navigation on v4.0.0-rc1. This will only be necessary this time as after the merge, we can create all new branches with the new LH navigation. It just does not yet exist on the production site so can't be linked to.

**Comment by NPJ-OP-LUX** [comment]
I have put the abstract text into the business overview, with some modification, at the beginning under the heading abstract. For discussion.

**Comment by NPJ-OP-LUX** [comment]
The branch merge has been completed and now v4.0.0-rc.1 has the updated navigation. All points addressed and complete.
